// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Dwc_IbM3yZQ5lq7srru0O3c8iwaJ7-w',
    appId: '1:400059907279:web:be45553e91258523c54bba',
    messagingSenderId: '400059907279',
    projectId: 'cloudmessaging-dfbb8',
    authDomain: 'cloudmessaging-dfbb8.firebaseapp.com',
    storageBucket: 'cloudmessaging-dfbb8.firebasestorage.app',
    measurementId: 'G-BV1SQ4R4RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJzxWr7HexgNVltB0ifianeMwyab-PNyc',
    appId: '1:400059907279:android:608ccfb4d8446b96c54bba',
    messagingSenderId: '400059907279',
    projectId: 'cloudmessaging-dfbb8',
    storageBucket: 'cloudmessaging-dfbb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcfcMpMo-l3MmNKua2uQZfTWWPaQaWeQU',
    appId: '1:400059907279:ios:76850ca6146d29ecc54bba',
    messagingSenderId: '400059907279',
    projectId: 'cloudmessaging-dfbb8',
    storageBucket: 'cloudmessaging-dfbb8.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcfcMpMo-l3MmNKua2uQZfTWWPaQaWeQU',
    appId: '1:400059907279:ios:76850ca6146d29ecc54bba',
    messagingSenderId: '400059907279',
    projectId: 'cloudmessaging-dfbb8',
    storageBucket: 'cloudmessaging-dfbb8.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Dwc_IbM3yZQ5lq7srru0O3c8iwaJ7-w',
    appId: '1:400059907279:web:912805169bff117dc54bba',
    messagingSenderId: '400059907279',
    projectId: 'cloudmessaging-dfbb8',
    authDomain: 'cloudmessaging-dfbb8.firebaseapp.com',
    storageBucket: 'cloudmessaging-dfbb8.firebasestorage.app',
    measurementId: 'G-QBN8WGJZ34',
  );
}
